### ISSUE TITLE
Very slow execution for middle to large datasets

### ISSUE THREAD

**Issue by omarcr** [markdregan/K-Nearest-Neighbors-with-Dynamic-Time-Warping#2]
Hi, is there any change in the code that you might recommend to speed up the execution of the algorithm?

**Comment by Nixonite** [comment]
DTW in general is O(n^2), so that's expected. You could look into this  https://en.wikipedia.org/wiki/Dynamic_time_warping#Fast_computation

**Comment by markdregan** [comment]
Sorry for delay - missed this. As @Nixonite mentioned, DTW is O(N^2) and it is used within a non-optimized naive KNN algorithm which is O(dN). Combining these, you get a model that doesn't scale well.
