### ISSUE TITLE
import numpy & scipy in knn_dtw_class.py

### ISSUE THREAD

**Issue by stgrmks** [markdregan/K-Nearest-Neighbors-with-Dynamic-Time-Warping#4]
np.shape & scipy.spatial.distance are being used w/o previous import of those modules.

**Comment by markdregan** [comment]
Thanks for flagging. I'll run through the notebooks in the coming weeks.

**Comment by markdregan** [comment]
Notebook has been updated to fix this issue.
knn_dtw_class.py has been removed to repo to avoid having to update two duplicate sources.

Thanks for flagging @stgrmks
